theme: jekyll-theme-minimal
title: Georgia Bullen
description: fuzzing the lines between tech, policy, design, data and organizing, but really just trying to help solve some problems. <br /> techpolicy / UX / design / data / dataviz / visualization / urbanplanning / civic / opensource.