theme: jekyll-theme-minimal
title: Georgia Bullen
description: Currently the Director of Technology Projects @New America's <a href="http://opentechinstitute.org">OTI</a>  #techpolicy #UX #design #data #dataviz #visualization #urbanplanning #civic #opensource.